### ISSUE TITLE
Media queries do not show up in browsers email clients

### ISSUE THREAD

**Issue by SarahVanDenBerghe** [resend/react-email#1095]
### Describe the Bug

The [fix of media queries](https://github.com/resend/react-email/pull/1019) using Tailwind, which is in 0.0.12 does not work for Gmail / Outlook in browser. It does work in Apple Mail (separate app). I thought perhaps it's Gmail / Outlook at fault, but it does seem to work for the HTML output that MJML outputs.

If I use the inspect I can't find the <style /> tag altogether.

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

/

### To Reproduce

1. Just use any code that has styling with a media query.
2. Send it to yourself, and test out on Outlook / Gmail in browser (tested on desktop).

### Expected Behavior

For the media queries to work.

**Comment by gabrielmfern** [comment]
Does it not work with `0.0.13` either?

**Comment by emlez** [comment]
Have you tried with only media-queries? A work-around I tend to use for Gmail ([as it doesn't fully support `@media`](https://www.caniemail.com/search/?s=media)) is that I use `max-width`, like this:

```jsx
<Container className="max-w-lg">
    {/* Your components in here */}
</Container>
```

You can try with `max-w-lg` or `max-w-screen-lg`, as it seems to vary a bit, on my experience.

**Comment by vctormb** [comment]
> @SarahVanDenBerghe, have you tried with only media-queries? A work-around I tend to use for Gmail ([as it doesn't fully support `@media`](https://www.caniemail.com/search/?s=media)) is that I use `max-width`, like this:
> 
> ```js
> <Container className="max-w-lg">
>     {/* Your components in here */}
> </Container>
> ```
> 
> You can try with `max-w-lg` or `max-w-screen-lg`, as it seems to vary a bit, on my experience.

interesting! could you provide a better example on how to replace media query with max-w-?

**Comment by jwarykowski** [comment]
@gabrielmfern just looking at this as I can see the same problem, I can see the underlying format has changed. For instance please see the differences between the old and new media queries produced for the same email:

`Old`
```css
<style>@media(min-width:640px){.sm_float_right{float: right !important;}.sm_float_left{float: left !important;}.sm_block{display: block !important;}.sm_hidden{display: none !important;}.sm_w_1_4{width: 25% !important;}.sm_w_2_4{width: 50% !important;}.sm_w_3_4{width: 75% !important;}.sm_min_w_37_5rem_{min-width: 37.5rem !important;}.sm_px_10{padding-left: 2.5rem !important;;padding-right: 2.5rem !important;}.sm_px_20{padding-left: 5rem !important;;padding-right: 5rem !important;}.sm_pt_9{padding-top: 2.25rem !important;}.sm_text_right{text-align: right !important;}}
```

`New`
```css
<style>@media(min-width:640px){.sm\:float-right{float:right!important}.sm\:float-left{float:left!important}.sm\:block{display:block!important}.sm\:hidden{display:none!important}.sm\:w-1\/2{width:50%!important}.sm\:w-1\/4{width:25%!important}.sm\:w-3\/4{width:75%!important}.sm\:px-10{padding-left:40px!important;padding-right:40px!important}.sm\:px-20{padding-left:80px!important;padding-right:80px!important}.sm\:pt-9{padding-top:36px!important}.sm\:text-right{text-align:right!important}}</style>
```

The bit that looks odd to me is the escaping slashes for the class names.  Why do we do this? 

`.sm\:float-right`

Note it [appears](https://pineco.de/css-quick-tip-the-valid-characters-in-a-custom-css-selector/#:~:text=A%20valid%20name%20should%20start,hyphen%20followed%20by%20a%20number.) that a `:` in a selector is invalid.
