### ISSUE TITLE
Tailwind `max` breakpoint modifiers don't work

### ISSUE THREAD

**Issue by ryanleichty** [resend/react-email#2297]
### Describe the Bug

Using a Tailwind max modifier like this `max-desktop:px-40` doesn't work due to a missing space in the output. For example, `max-desktop:px-40` outputs this:

```css
@media not all and(min-width:600px) {
  .max-desktop_px-40 {
    padding-left: 40px !important;
    padding-right: 40px !important
  }
}
```

The issue is caused by the missing space here: `and(min-width:600px)`. It should be `and (min-width:600px)` with a space after the keyword `and` in order for it to work.

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

NA

### To Reproduce

Add [a max modifier](https://v3.tailwindcss.com/docs/responsive-design#targeting-a-breakpoint-range) like `max-sm:px-40` and check if the style is being applied or not.

### Expected Behavior

Using a `max-*` breakpoint modifier should work and output the correct CSS.
